name: Web Dev V2

on:
  workflow_dispatch:
    inputs:
        tag:
          type: string
          required: true
          description: Release Tag
          default: v2.0.0

env:
  DOCKER_IMAGE: ${{ vars.DOCKER_REPOSITORY }}/frontend

jobs:
  deploy_to_dev:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Node version bump
        run: npm version --no-commit-hooks --allow-same-version --no-git-tag-version ${{ inputs.tag }}
      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.tag }}
          generateReleaseNotes: true
          commit: ${{ github.sha }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: release
          branch: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
